# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: filippo.fontanelli
email: info@fontanellif.it
description: > # "Hi! Welcome to Fontanellif's home page. Research, projects, blog or send him an email."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Awhy
    url: http://www.awhy.it
  - title: github
    url: https://github.com/fontanellif
  - title: linkedin
    url: 
  - title: tuOtempO
    url: http://www.tuotempo.com
